name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PowerShell command
        shell: pwsh
        run: |
          Write-Host "Hello, Shreya! This is your first GitHub workflow."
          Get-Date
